#if !(os(macOS) || os(iOS) || os(tvOS) || os(watchOS))
import XCTest

extension CAtomicsBasicTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CAtomicsBasicTests = [
        ("testAtomicMutableRawPointer", testAtomicMutableRawPointer),
        ("testAtomicOpaquePointer", testAtomicOpaquePointer),
        ("testAtomicOptionalMutableRawPointer", testAtomicOptionalMutableRawPointer),
        ("testAtomicOptionalOpaquePointer", testAtomicOptionalOpaquePointer),
        ("testAtomicOptionalRawPointer", testAtomicOptionalRawPointer),
        ("testAtomicRawPointer", testAtomicRawPointer),
        ("testAtomicTaggedMutableRawPointer", testAtomicTaggedMutableRawPointer),
        ("testAtomicTaggedOptionalMutableRawPointer", testAtomicTaggedOptionalMutableRawPointer),
        ("testAtomicTaggedOptionalRawPointer", testAtomicTaggedOptionalRawPointer),
        ("testAtomicTaggedRawPointer", testAtomicTaggedRawPointer),
        ("testBool", testBool),
        ("testFence", testFence),
        ("testInt", testInt),
        ("testInt16", testInt16),
        ("testInt32", testInt32),
        ("testInt64", testInt64),
        ("testInt8", testInt8),
        ("testTaggedMutableRawPointer", testTaggedMutableRawPointer),
        ("testTaggedOptionalMutableRawPointer", testTaggedOptionalMutableRawPointer),
        ("testTaggedOptionalRawPointer", testTaggedOptionalRawPointer),
        ("testTaggedRawPointer", testTaggedRawPointer),
        ("testUInt", testUInt),
        ("testUInt16", testUInt16),
        ("testUInt32", testUInt32),
        ("testUInt64", testUInt64),
        ("testUInt8", testUInt8),
    ]
}

extension CAtomicsRaceTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CAtomicsRaceTests = [
        ("testRaceCrash", testRaceCrash),
        ("testRacePointerCAS", testRacePointerCAS),
        ("testRacePointerSwap", testRacePointerSwap),
        ("testRaceSpinLock", testRaceSpinLock),
        ("testRaceTaggedPointerCAS", testRaceTaggedPointerCAS),
    ]
}

extension MemoryOrderTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__MemoryOrderTests = [
        ("testMemoryOrder", testMemoryOrder),
    ]
}

extension UnmanagedRaceTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__UnmanagedRaceTests = [
        ("testRaceAtomickishUnmanaged", testRaceAtomickishUnmanaged),
        ("testRaceLoadVersusDeinit", testRaceLoadVersusDeinit),
    ]
}

extension UnmanagedTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__UnmanagedTests = [
        ("testDemonstrateWhyLockIsNecessary", testDemonstrateWhyLockIsNecessary),
        ("testSpinLoad", testSpinLoad),
        ("testSpinSwap", testSpinSwap),
        ("testSpinTake", testSpinTake),
        ("testStrongCASFailure", testStrongCASFailure),
        ("testStrongCASSuccess", testStrongCASSuccess),
        ("testUnmanaged", testUnmanaged),
        ("testWeakCasBlocked", testWeakCasBlocked),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(CAtomicsBasicTests.__allTests__CAtomicsBasicTests),
        testCase(CAtomicsRaceTests.__allTests__CAtomicsRaceTests),
        testCase(MemoryOrderTests.__allTests__MemoryOrderTests),
        testCase(UnmanagedRaceTests.__allTests__UnmanagedRaceTests),
        testCase(UnmanagedTests.__allTests__UnmanagedTests),
    ]
}
#endif
